(function(){'use strict';var c;c||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,g="undefined"!=typeof WorkerGlobalScope,k="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,ba=window.__eaglercraftXLoaderContextPre.loaderWASMURL;c.locateFile=function(a){return"loader.wasm"===a?ba:a};
var t=window.__eaglercraftXLoaderContextPre.rootElement,ca=window.__eaglercraftXLoaderContextPre.eaglercraftXOpts,u=window.__eaglercraftXLoaderContextPre.theEPWFileBuffer,da=window.__eaglercraftXLoaderContextPre.splashURL;delete window.__eaglercraftXLoaderContextPre;var v=[null];
function w(){for(var a=null,b;b=t.lastChild;)a||=b,t.removeChild(b);b=document.createElement("div");b.classList.add("_eaglercraftX_wrapper_element");b.setAttribute("style","position:relative;width:100%;height:100%;overflow:hidden;");a&&(a.classList.add("_eaglercraftX_early_splash_element"),a.style.position="absolute",a.style.top="0px",a.style.left="0px",a.style.right="0px",a.style.bottom="0px",a.style.zIndex="2",b.appendChild(a));t.appendChild(b);return b}function x(){c=y=z=A=B=null}
var C=[],D="./this.program",E=(a,b)=>{throw b;},F="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?F=__filename:g&&(F=self.location.href);var G="",J,K;
if(k){var fs=require("fs");require("path");G=__dirname+"/";K=a=>{a=L(a)?new URL(a):a;return fs.readFileSync(a)};J=async a=>{a=L(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(D=process.argv[1].replace(/\\/g,"/"));C=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=c);E=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||g){try{G=(new URL(".",F)).href}catch{}g&&(K=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
J=async a=>{if(L(a))return new Promise((d,e)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?d(f.response):e(f.status)};f.onerror=e;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var M=console.error.bind(console),N,y,O=!1,z,A,B,L=a=>a.startsWith("file://");
function P(){var a=y.buffer;new Int8Array(a);new Int16Array(a);z=new Uint8Array(a);new Uint16Array(a);A=new Int32Array(a);B=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var Q=0,R=null,S;async function ea(a){if(!N)try{var b=await J(a);return new Uint8Array(b)}catch{}if(a==S&&N)a=new Uint8Array(N);else if(K)a=K(a);else throw"both async and sync fetching of the wasm failed";return a}
async function fa(a,b){try{var d=await ea(a);return await WebAssembly.instantiate(d,b)}catch(e){throw M(`failed to asynchronously prepare wasm: ${e}`),a=e,c.onAbort?.(a),a="Aborted("+a+")",M(a),O=!0,new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}}
async function ha(a){var b=S;if(!N&&"function"==typeof WebAssembly.instantiateStreaming&&!L(b)&&!k)try{var d=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(e){M(`wasm streaming compile failed: ${e}`),M("falling back to ArrayBuffer instantiation")}return fa(b,a)}class U{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ia=a=>{for(;0<a.length;)a.shift()(c)},ja=[],ka=[],la=()=>{var a=c.preRun.shift();ka.push(a)},ma=!0,V="undefined"!=typeof TextDecoder?new TextDecoder:void 0,W=(a=0)=>{for(var b=z,d=a+NaN,e=a;b[e]&&!(e>=d);)++e;if(16<e-a&&b.buffer&&V)return V.decode(b.subarray(a,e));for(d="";a<e;){var f=b[a++];if(f&128){var r=b[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|r);else{var m=b[a++]&63;f=224==(f&240)?(f&15)<<12|r<<6|m:(f&7)<<18|r<<12|m<<6|b[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,
d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},na=a=>{ma||(c.onExit?.(a),O=!0);E(a,new U(a))};c.noExitRuntime&&(ma=c.noExitRuntime);c.printErr&&(M=c.printErr);c.wasmBinary&&(N=c.wasmBinary);c.arguments&&(C=c.arguments);c.thisProgram&&(D=c.thisProgram);
var oa={c:function(a){console.error("LoaderMain: [ERROR] "+(a?W(a):""))},b:function(a){console.log("LoaderMain: [INFO] "+(a?W(a):""))},j:a=>{var b=z.length;a>>>=0;if(67108864<a)return!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(67108864,65536*Math.ceil(Math.max(a,e)/65536))-y.buffer.byteLength+65535)/65536|0;try{y.grow(e);P();var f=1;break a}catch(r){}f=void 0}if(f)return!0}return!1},m:function(){return u.byteLength},i:function(){return"undefined"!==typeof WebAssembly.Suspending},
f:function(a,b){const d=v.length;v.push(V.decode(new Uint8Array(u,a,b)));return d},e:function(a){const b=v.length;v.push(new Uint8Array(a));return b},d:function(a,b,d){z.set(new Uint8Array(u,b,d),a)},g:function(a,b,d,e){v[a].set(new Uint8Array(u,d,e),b)},k:function(a,b,d,e){v[a].set(new Uint8Array(z.buffer,b,e),d)},a:function(a){u=v=null;setTimeout(x,20);const b=w(),d=document.createElement("div");d.setAttribute("style","z-index:100;position:absolute;top:10%;left:10%;right:10%;bottom:10%;background-color:white;border:2px solid #cccccc;overflow-x:hidden;overflow-y:scroll;");
d.classList.add("_eaglercraftX_loader_failed_container");a=a?W(a):"";console.error("LoaderMain: [FAILED] "+a);const e=document.createElement("h2");e.style.color="#AA0000";e.style.padding="25px";e.style.fontFamily="sans-serif";e.style.marginBlock="0px";e.appendChild(document.createTextNode(a));d.appendChild(e);a=document.createElement("h4");a.style.color="#AA0000";a.style.padding="25px";a.style.fontFamily="sans-serif";a.style.marginBlock="0px";a.appendChild(document.createTextNode("Try again later"));
d.appendChild(a);b.appendChild(d)},h:function(a){var b=a>>2;a=v[A[b]];var d=v[A[b+1]];a=a?URL.createObjectURL(new Blob([a],{type:d||"image/png"})):null;b=(b=v[A[b+2]])?V.decode(b):"<h1>Failed to load error screen</h1>";u=v=null;setTimeout(x,20);d=w();var e=document.createElement("img");e.setAttribute("style","z-index:100;position:absolute;top:10px;left:calc(50% - 151px);");e.src=a;d.appendChild(e);a=document.createElement("div");a.setAttribute("style","z-index:100;position:absolute;top:135px;left:10%;right:10%;bottom:50px;background-color:white;border:2px solid #cccccc;");
a.classList.add("_eaglercraftX_jspi_unsupported_container");e=document.createElement("iframe");e.classList.add("_eaglercraftX_jspi_unsupported_frame");e.setAttribute("style","border:none;width:100%;height:100%;");e.srcdoc=b;a.appendChild(e);d.appendChild(a)},l:function(a){a>>=2;const b=URL.createObjectURL(new Blob([v[A[a]]],{type:"text/javascript;charset=utf-8"})),d=URL.createObjectURL(new Blob([v[A[a+1]]],{type:"application/wasm"})),e=URL.createObjectURL(new Blob([v[A[a+2]]],{type:"application/octet-stream"})),
f=URL.createObjectURL(new Blob([v[A[a+3]]],{type:"application/wasm"})),r=URL.createObjectURL(new Blob([v[A[a+4]]],{type:v[A[a+5]]})),m=URL.createObjectURL(new Blob([v[A[a+6]]],{type:v[A[a+7]]})),T=URL.createObjectURL(new Blob([v[A[a+8]]],{type:v[A[a+9]]})),H=A[a+10],q=Array(H);for(var h=0,l;h<H;++h)l=a+11+3*h,q[h]={data:v[A[l]],name:v[A[l+1]],path:v[A[l+2]]};u=v=null;setTimeout(x,20);window.__eaglercraftXLoaderContext={getEaglercraftXOpts:function(){return ca},getEagRuntimeJSURL:function(){return b},
getClassesWASMURL:function(){return d},getClassesDeobfWASMURL:function(){return f},getClassesTEADBGURL:function(){return e},getEPKFiles:function(){return q},getRootElement:function(){return t},getMainArgs:function(){return[]},getImageURL:function(p){switch(p){case 0:return da;case 1:return r;case 2:return m;case 3:return T;default:return null}},runMain:function(p){setTimeout(p,10)}};a=document.createElement("script");a.type="text/javascript";a.src=b;document.head.appendChild(a)}},X;
(async function(){function a(d){X=d.exports;y=X.n;P();Q--;c.monitorRunDependencies?.(Q);0==Q&&R&&(d=R,R=null,d());return X}Q++;c.monitorRunDependencies?.(Q);var b={a:oa};if(c.instantiateWasm)return new Promise(d=>{c.instantiateWasm(b,(e,f)=>{d(a(e,f))})});S??=c.locateFile?c.locateFile("loader.wasm",G):G+"loader.wasm";return a((await ha(b)).instance)})();var pa=c._main=(a,b)=>(pa=c._main=X.p)(a,b),Y=a=>(Y=X.q)(a);
function qa(a=[]){var b=pa;a.unshift(D);var d=a.length,e=Y(4*(d+1)),f=e;a.forEach(m=>{for(var T=B,H=f>>2,q=0,h=0;h<m.length;++h){var l=m.charCodeAt(h);127>=l?q++:2047>=l?q+=2:55296<=l&&57343>=l?(q+=4,++h):q+=3}var p=q+1;h=q=Y(p);l=z;if(0<p){p=h+p-1;for(var I=0;I<m.length;++I){var n=m.charCodeAt(I);if(55296<=n&&57343>=n){var ra=m.charCodeAt(++I);n=65536+((n&1023)<<10)|ra&1023}if(127>=n){if(h>=p)break;l[h++]=n}else{if(2047>=n){if(h+1>=p)break;l[h++]=192|n>>6}else{if(65535>=n){if(h+2>=p)break;l[h++]=
224|n>>12}else{if(h+3>=p)break;l[h++]=240|n>>18;l[h++]=128|n>>12&63}l[h++]=128|n>>6&63}l[h++]=128|n&63}}l[h]=0}T[H]=q;f+=4});B[f>>2]=0;try{var r=b(d,e);na(r)}catch(m){m instanceof U||"unwind"==m||E(1,m)}}
function Z(a=C){function b(){c.calledRun=!0;if(!O){X.o();c.onRuntimeInitialized?.();c.noInitialRun||qa(a);if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var d=c.postRun.shift();ja.push(d)}ia(ja)}}if(0<Q)R=Z;else{if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)la();ia(ka);0<Q?R=Z:c.setStatus?(c.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>c.setStatus(""),1);b()},1)):b()}}
if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.shift()();Z();}).call(this);
